### ISSUE TITLE
code is not working can u find answer for this input file.....

### ISSUE THREAD

**Issue by nick8359** [Ras-al-Ghul/Karger-Mincut-Code#1]
[kargerMinCut.txt](https://github.com/Ras-al-Ghul/Karger-Mincut-Code/files/817814/kargerMinCut.txt)

**Comment by Ras-al-Ghul** [comment]
If it is a segmentation fault you're getting, it's because of shortage of stack space. Try on a smaller input file if you'd like to confirm.
On CodeBlocks, the commands it runs (after allocating more stack space) are:

`mingw32-g++.exe   -c H:\GitHub\Karger-Mincut-Code\kargermincut.cpp -o H:\GitHub\Karger-Mincut-Code\kargermincut.o`
`mingw32-g++.exe  -o H:\GitHub\Karger-Mincut-Code\kargermincut.exe H:\GitHub\Karger-Mincut-Code\kargermincut.o  -Wl,--stack,1368435456`

The Linux commands should be similar.

It was the same 200 line input file when I took the course and I ran the code right now. It works.
I won't be giving out the answer. You could refer to this and optimize your own code to use less space or somehow allocate more stack space to this code.
